### ISSUE TITLE
dnslib issue 

### ISSUE THREAD

**Issue by ghost** [daeken/httprebind#3]
hi when running the tool i get this error 
Traceback (most recent call last):
  File "httprebind.py", line 6, in <module>
    from dnslib import *
ImportError: No module named dnslib
i already ran pip install dnslib
Requirement already satisfied: dnslib in /usr/lib/python3/dist-packages (0.9.10)
was wondering how to fix this issue

**Comment by ghost** [comment]
now facing another issue.
File "httprebind.py", line 70
    print 'DNS request for:', str(qname).strip('.')
                           ^
SyntaxError: invalid syntax

**Comment by daeken** [comment]
You're trying to run httprebind with Python3 (and dnslib installed there) -- that won't work.  You'll need to run it via Python2 and install dnslib via the appropriate pip.
